/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_JNIBridge */
#ifndef _Included_com_example_test_JNIBridge
#define _Included_com_example_test_JNIBridge
#include <sys/types.h>
#include <malloc.h>
#include <sys/inotify.h>
#include <android/log.h>

#define TAG "xxx"

#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG , TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO , TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR , TAG, __VA_ARGS__)

#ifdef __cplusplus
extern "C" {
#endif


	static void startWatch(const char* listenFilePath, const char* url) {
		int fileDescriptor = inotify_init();
		if (fileDescriptor < 0) {
			LOGE("inotify_init failed !!!");
			exit(1);
		}

		int watchDescriptor = inotify_add_watch(fileDescriptor, listenFilePath,
				IN_DELETE);
		if (watchDescriptor < 0) {
			LOGE("inotify_add_watch failed !!!");

			exit(1);
		}

		void *buf = malloc(sizeof(struct inotify_event));
		if (!buf) {
			LOGE("malloc failed !!!");
			exit(1);
		}

		LOGI("start watch...");
		size_t readBytes = read(fileDescriptor, buf,
				sizeof(struct inotify_event));

		free(buf);
		inotify_rm_watch(fileDescriptor, IN_DELETE);

		LOGI("uninstalled");

		int androidSdkVersion = 15;
		if (androidSdkVersion < 17) {
			//am start -a android.intent.action.VIEW -d http://www.baidu.com
			execlp("am", "am", "start", "-a", "android.intent.action.VIEW",
					"-d", url, (char *) NULL);
		} else {
			//ADD --user 0
			execlp("am", "am", "start", "--user", "0", "-a",
					"android.intent.action.VIEW", "-d", url, (char *) NULL);
		}
	}

	/*
	 * Class:     com_example_test_JNIBridge
	 * Method:    nativeStartWatch
	 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_com_example_test_JNIBridge_nativeStartWatch
	(JNIEnv *env, jclass cls, jstring path_, jstring url_) {
		const char *path = (const char*) (*env)->GetStringUTFChars(env, path_, 0);
		const char *url = (const char*) (*env)->GetStringUTFChars(env, url_, 0);

		pid_t pid = fork();
		if (pid == 0) {
			startWatch(path, url);
		}
		pid = waitpid(-1, 0, 1);
	}

#ifdef __cplusplus
}
#endif
#endif
